### ISSUE TITLE
[QUESTION] : Translations files

### ISSUE THREAD

**Issue by ZiZuu-store** [PrestaShop/ganalytics#64]
there are two translation files locations on this (and some other) module .. the root dir and the `translations` dir. The first being older ...

`fr.php` is present in both locations and seems to be a duplicate (not in sync) ..

Am I missing something or translations should all being grouped in the relative folder?

Thank you

**Comment by Quetzacoalt91** [comment]
Hi,

Good catch !
They should be in the root folder to keep the compatibility with PrestaShop 1.4.

Best regards

**Comment by ZiZuu-store** [comment]
Oh my God :)  

what about to put them in the "modern" translations folder and add a backward compatibility method that will move them on install/update if PS version is <1.5 ?

For the sake of cleanness and readability ;)
