### ISSUE TITLE
Enhanced ecommerce steps no longer working

### ISSUE THREAD

**Issue by pierreavizou** [PrestaShop/ganalytics#78]
Hello, 

Since the last update (version 2.3.2), checkout steps are no longer tracked. In Analytics, in the "purchase behavior analysis" section, all transactions go directly from "step 0" to "transaction". See file attached.

EDIT : Our PrestaShop version is 1.6.0.11. 

![capture d ecran 2015-11-09 a 14 48 26](https://cloud.githubusercontent.com/assets/7101583/11035181/f2ada97a-86f0-11e5-9349-0062412b69e7.png)

**Comment by pierreavizou** [comment]
Update: The concerned version is version 2.3.2, not 2.2.3, it was a typo, I fixed it in my initial message. 
Sorry about that, and thanks for investigating the issue. 
If anyone can confirm or not that they are also having the issue that would be great. 
Thank you.

**Comment by justb81** [comment]
i can confirm that issue! Beginning with the 9th november (the day we updated to 2.3.2), all steps but the last are gone.

Prestashop is 1.6.1.2-3 and the issue still exists in module version 2.3.3

**Comment by pierreavizou** [comment]
Fixed in PR #90
