### ISSUE TITLE
Old orders are sent to Google Analytics if module is not installed from start

### ISSUE THREAD

**Issue by morgan-enetb** [PrestaShop/ganalytics#79]
With this code in hookBackOfficeHeader, each time you consult order and this order is not in the database ps_ganalytics, a record is created and send old transaction.It should not send orders made before the module installation

<pre><code>
if ($this->context->controller->controller_name == 'AdminOrders')
			{
				if (Tools::getValue('id_order'))
				{
					$ga_order_sent = Db::getInstance()->getValue('SELECT id_order FROM `'._DB_PREFIX_.'ganalytics` WHERE id_order = '.(int)Tools::getValue('id_order'));
					if ($ga_order_sent === false)
						Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'ganalytics` (id_order, id_shop, sent, date_add) VALUES ('.(int)Tools::getValue('id_order').', '.(int)$this->context->shop->id.', 0, NOW())');
				}
				else
</code></pre>

**Comment by cedricfontaine** [comment]
You're right, I added a verification to add only orders less than 1 day old.

**Comment by vincentbz** [comment]
Agreed for this, possible to have a core review by PS ? @Quetzacoalt91 for example :dancers:

**Comment by cedricfontaine** [comment]
It has already been implemented in the module.

**Comment by julienbourdeau** [comment]
Closed with #83
